FROM maven:3.5.2-jdk-8-alpine AS MAVEN_BUILD

MAINTAINER Longlt

COPY pom.xml /build/
COPY src /build/src/

WORKDIR /build/
RUN mvn package

FROM openjdk:8-jre-alpine

WORKDIR /app

COPY --from=MAVEN_BUILD /build/target/SpringCloudConfigServer-0.0.1-SNAPSHOT /app/

ENTRYPOINT ["java", "-jar", "SpringCloudConfigServer-0.0.1-SNAPSHOT.jar"]